name: 'Greeting'
description: 'Greet someone'
inputs:
  first_name:
    description: 'Who to greet'
    required: true
  last_name:
    description: 'Who to greet'
    required: true
runs:
  using: 'docker'
  main: 'Dockerfile'